require("spec.support.playdate_stub")
import "TapOrReel"

-- One frame of the button: returns degrees to reel in, and whether the button was tapped
local function frame(button, state, crankChange)
    return button:update(state == "pressed", state == "pressed" or state == "held", state == "released", crankChange or 0)
end

describe("TapOrReel", function()
    it("is a tap when pressed and let go without cranking", function()
        local button = TapOrReel.new()
        assert.are.same({ 0, false }, { frame(button, "pressed") })
        assert.are.same({ 0, false }, { frame(button, "held") })
        assert.are.same({ 0, true }, { frame(button, "released") })
    end)

    it("reels in by as much as the crank is turned backwards while held", function()
        local button = TapOrReel.new()
        frame(button, "pressed")
        assert.are.same({ 10, false }, { frame(button, "held", -10) })
        assert.are.same({ 25, false }, { frame(button, "held", -25) })
    end)

    it("is not a tap once it has reeled", function()
        local button = TapOrReel.new()
        frame(button, "pressed")
        frame(button, "held", -10)
        assert.are.same({ 0, false }, { frame(button, "released") })
    end)

    it("does not reel when the crank goes forwards", function()
        local button = TapOrReel.new()
        frame(button, "pressed")
        assert.are.same({ 0, false }, { frame(button, "held", 30) })
        assert.are.same({ 0, true }, { frame(button, "released") })
    end)

    it("ignores a crank that barely trembles, so a tap stays a tap", function()
        local button = TapOrReel.new()
        frame(button, "pressed")
        assert.are.same({ 0, false }, { frame(button, "held", -1) })
        assert.are.same({ 0, true }, { frame(button, "released") })
    end)

    it("does nothing while the button is up, however the crank turns", function()
        local button = TapOrReel.new()
        assert.are.same({ 0, false }, { frame(button, "up", -90) })
    end)

    it("knows when it is held, so the crank can stop turning the view", function()
        local button = TapOrReel.new()
        assert.is_false(button:isHeld())
        frame(button, "pressed")
        assert.is_true(button:isHeld())
        frame(button, "released")
        assert.is_false(button:isHeld())
    end)

    it("can be told to ignore a press that was spent on something else", function()
        local button = TapOrReel.new()
        frame(button, "pressed")
        button:ignoreThisPress()
        assert.are.same({ 0, false }, { frame(button, "held", -40) })
        assert.are.same({ 0, false }, { frame(button, "released") })
    end)

    it("starts afresh with the next press", function()
        local button = TapOrReel.new()
        frame(button, "pressed")
        frame(button, "held", -40)
        frame(button, "released")
        frame(button, "pressed")
        assert.are.same({ 0, true }, { frame(button, "released") })
    end)
end)
